package com.chinarewards.elt.service.staff.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.chinarewards.elt.dao.org.ImportStaffCodeDao;
import com.chinarewards.elt.domain.org.ImportStaffCode;
import com.chinarewards.elt.model.staff.ImportStaffCodeData;
import com.chinarewards.elt.model.staff.ImportStaffCodeData.ParserCode;
import com.chinarewards.elt.model.staff.ImportStaffParser;
import com.chinarewards.elt.model.staff.ImportStaffParser.ParserMethod;
import com.chinarewards.elt.service.staff.ImportStaffCodeLogic;
import com.google.inject.Inject;

/**
 * The implementation of business logic bean for import code operation
 * 
 * @author sunhongliang
 * @since 1.0.0 2010-07-05
 */
public class ImportStaffCodeLogicImpl implements ImportStaffCodeLogic {

	private final ImportStaffCodeDao importCodeDao;
	private static boolean isAutoGenerated = false;

	@Inject
	public ImportStaffCodeLogicImpl(ImportStaffCodeDao importCodeDao) {
		this.importCodeDao = importCodeDao;
	}

	protected void prepareImportStaffCode() {
		// manually create import staff code when the method getAll is firstly invoked
		if (!isAutoGenerated) {
			try {
				Map<Long, ParserMethod> tmp = new HashMap<Long, ParserMethod>(); 
				List<ParserMethod> list2 = ImportStaffParser.getAllImportStaffMethod();
				for (ParserMethod method : list2) {
					tmp.put(method.getCode(), method);
				}
				List<ParserCode> list = ImportStaffCodeData.getAllImportStaffCode();
				for (ParserCode pcode : list) {
					ImportStaffCode code = findByCode(pcode.getCode());
					if (code == null) {
						code = new ImportStaffCode();
						code.setCode(pcode.getCode());
						code.setMessage(pcode.getMessage());
						code.setPriority(pcode.getPriority());
						code.setType(pcode.getType());
						code.setParserMethod(tmp.get(pcode.getCode()).getParserMethod());
						insertImportCode(code);
					} else {
						code.setMessage(pcode.getMessage());
						code.setPriority(pcode.getPriority());
						code.setType(pcode.getType());
						code.setParserMethod(tmp.get(pcode.getCode()).getParserMethod());
						importCodeDao.update(code);
					}
				}
			} catch (Exception e) {
				e.printStackTrace();
			}
			isAutoGenerated = true;
		}
	}
	
	@Override
	public List<ImportStaffCode> getAll() {
		prepareImportStaffCode();
		return importCodeDao.getAll();
	}

	@Override
	public ImportStaffCode findByCode(Long code) {
		return importCodeDao.findByCode(code);
	}

	@Override
	public ImportStaffCode insertImportCode(ImportStaffCode code) {
		return importCodeDao.save(code);
	}

}
